port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /usr/local/clash/ui
#TCPå¹¶å‘è¿æ¥å°†ä½¿ç”¨æ‰€æœ‰IPè¿›è¡ŒTCPæ¡æ‰‹ï¼Œå¹¶ä½¿ç”¨æœ€å…ˆæ¡æ‰‹çš„IPè¿›è¡Œåç»­è¯·æ±‚,é»˜è®¤ä¸ºfalse
tcp-concurrent: true
# DNSæœåŠ¡å™¨
dns:
  # å¼€å¯Clashå†…ç½®DNSæœåŠ¡å™¨
  # é»˜è®¤ä¸ºfalse
  enable: true
  # æ¨¡å¼fake-ip
  enhanced-mode: fake-ip
  # DNSç›‘å¬ç«¯å£
  listen: 0.0.0.0:9053
  fake-ip-range: 12.0.0.1/16
proxies:
  - {name: å³°å€¼é€Ÿåº¦1 5589 KB/s, server: 104.16.151.69, port: 80, type: vless, uuid: 2e632913-bae0-4855-893c-02c828c835a2, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-calm-rice-56e5.hebe061103.workers.dev}}}
  - {name: å³°å€¼é€Ÿåº¦2 5858 KB/s, server: 104.17.84.132, port: 80, type: vless, uuid: 3ada7b0b-4734-448f-adc6-b88a40f65518, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-dark-breeze-d0d7.hebe061103.workers.dev}}}
  - {name: å³°å€¼é€Ÿåº¦3 5249 KB/s, server: 162.159.18.79, port: 80, type: vless, uuid: 27b9fc10-48a1-42e4-aef1-aef97860fa3a, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-noisy-feather-0a79.hebe061103.workers.dev}}}
  - {name: å³°å€¼é€Ÿåº¦4 5499 KB/s, server: 104.16.231.4, port: 80, type: vless, uuid: efe6c33a-5bb7-4aa6-aa79-ad43fe7f86ad, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-wild-wave-7a34.hebe061103.workers.dev}}}
  - {name: å³°å€¼é€Ÿåº¦5 5659 KB/s, server: 104.19.202.60, port: 80, type: vless, uuid: 0cadcba3-7a09-474d-a4a6-74636407ff19, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-proud-voice-9777.hebe061103.workers.dev}}}
  # ä»¥ä¸Šä¸ºä»£ç†åœ°å€è¯·æ’å…¥
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸  è‡ªåŠ¨é€‰æ‹©
      - âš–ï¸  è´Ÿè½½å‡è¡¡-è½®è¯¢
      - âš–ï¸  è´Ÿè½½å‡è¡¡-æ•£åˆ—
      - å³°å€¼é€Ÿåº¦1 5589 KB/s
      - å³°å€¼é€Ÿåº¦2 5858 KB/s
      - å³°å€¼é€Ÿåº¦3 5249 KB/s
      - å³°å€¼é€Ÿåº¦4 5499 KB/s
      - å³°å€¼é€Ÿåº¦5 5659 KB/s
      # ä»¥ä¸Šä¸ºèŠ‚ç‚¹é€‰æ‹©ç»„çš„è‡ªåŠ¨é€‰æ‹©ä»£ç†è¯·æ’å…¥
  - name: â™»ï¸  è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - å³°å€¼é€Ÿåº¦1 5589 KB/s
      - å³°å€¼é€Ÿåº¦2 5858 KB/s
      - å³°å€¼é€Ÿåº¦3 5249 KB/s
      - å³°å€¼é€Ÿåº¦4 5499 KB/s
      - å³°å€¼é€Ÿåº¦5 5659 KB/s
      # ä»¥ä¸Šä¸ºè‡ªåŠ¨é€‰æ‹©ç»„ä¸‹é¢çš„ä»£ç†åœ°å€è¯·æ’å…¥
  - name: âš–ï¸  è´Ÿè½½å‡è¡¡-è½®è¯¢
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: round-robin
    proxies:
      - å³°å€¼é€Ÿåº¦1 5589 KB/s
      - å³°å€¼é€Ÿåº¦2 5858 KB/s
      - å³°å€¼é€Ÿåº¦3 5249 KB/s
      - å³°å€¼é€Ÿåº¦4 5499 KB/s
      - å³°å€¼é€Ÿåº¦5 5659 KB/s
      # ä»¥ä¸Šä¸ºè½®è¯¢ç»„ä¸‹é¢çš„ä»£ç†åœ°å€è¯·æ’å…¥
  - name: âš–ï¸  è´Ÿè½½å‡è¡¡-æ•£åˆ—
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: consistent-hashing
    proxies:
      - å³°å€¼é€Ÿåº¦1 5589 KB/s
      - å³°å€¼é€Ÿåº¦2 5858 KB/s
      - å³°å€¼é€Ÿåº¦3 5249 KB/s
      - å³°å€¼é€Ÿåº¦4 5499 KB/s
      - å³°å€¼é€Ÿåº¦5 5659 KB/s
      # ä»¥ä¸Šä¸ºæ•£åˆ—ç»„ä¸‹é¢çš„ä»£ç†åœ°å€è¯·æ’å…¥
rules:
 - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
